Шаблонизируй это
htmlacademy-ecmascript/1969965-big-trip-20 pull request #4
Opened 2023-05-08 20:48 UTC by JulianaAstra

2023-05-10 04:46 UTC, Dima-Dim requested changes

2023-05-10 04:46 UTC, Dima-Dim commented on src/constants.js
> +  {type: 'taxi'},
В данный момент довольно странно выглядит массив объектов, в которых только 1 ключ. У тебя есть какие-то  планы по добавлению ключей? Если да, то хорошо, если нет, то достаточно массива строк.

2023-05-10 04:46 UTC, Dima-Dim commented on src/constants.js
> +const DATE_FORMATS = {
https://up.htmlacademy.ru/ecmascript/20/criteries#b7

2023-05-10 04:46 UTC, Dima-Dim commented on src/constants.js
> +const FAVOURITE_BTN_STATE_CLASSES = {
https://up.htmlacademy.ru/ecmascript/20/criteries#b7

2023-05-10 04:46 UTC, Dima-Dim commented on src/utils.js
> +function formatDate(date, format) {
https://up.htmlacademy.ru/ecmascript/20/criteries#d5

2023-05-10 09:57 UTC, JulianaAstra commented on src/constants.js
> +  {type: 'taxi'},
Да, что-то у меня с массивом не получалась логика, придумался такой костыль)) подумаю, как сделать нормально

2023-05-11 05:06 UTC, Dima-Dim commented on src/constants.js
> +const tripTypes = ['taxi', 'bus','train', 'ship', 'drive', 'flight','check-in', 'sightseeing', 'restaurant'];
https://up.htmlacademy.ru/ecmascript/20/criteries#b5

2023-05-11 05:06 UTC, Dima-Dim commented on src/constants.js
> +  return BLANK_EVENT_FORM_DATA;
Зачем для этого функция? Тот же вопрос по остальным местам, где функция ничего не делает и просто возвращает константу или какое то значение.

2023-05-11 05:06 UTC, merged